### ISSUE TITLE
App crashes on launch with CLI >=v.2.2.3

### ISSUE THREAD

**Issue by Jvlsc** [calexandru2018/linux-gui-legacy#72] opened 2020-05-31 02:40 UTC
**Desktop OS:** Debian 10 (X11).

**The error:**

```
sudo protonvpn-gui
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn-gui", line 6, in <module>
    from protonvpn_linux_gui.gui import initialize_gui
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_linux_gui/gui.py", line 16, in <module>
    from .utils import (
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_linux_gui/utils.py", line 12, in <module>
    from protonvpn_cli.utils import (
ImportError: cannot import name 'make_ovpn_template' from 'protonvpn_cli.utils' (/usr/local/lib/python3.7/dist-packages/protonvpn_cli/utils.py)
```

Thank you for the work. I really appreciate it.

Kind regards.

**Comment by calexandru2018** [comment] 2020-05-31 08:26
Hi @Dvlnst  :)

I would really appreciate if you fill the template as much as you can, as I see that there is some crucial information that I would need, in help to provide you with some help.

Nonetheless, I suspect that the issue is due to that you are using CLI v.2.2.3. That version has deprecated the `make_ovpn_template` function. This is already fixed, although not pushed to master branch nor to PyPi due to some other updates that the GUI will suffer. <b>Either way, this should be fixed during this week, #71 </b>

<b>Temporary solution:</b> Downgrade CLI to v2.2.2

<b>Note: </b> I will not be closing this issue for now, since other users might be experiencing the same thing.

**Comment by s75uiFbxnykgkQMC7NQh** [comment] 2020-05-31 10:49
I confirm the exact ussie running Ubuntu 20.04.

**Comment by arch-btw** [comment] 2020-06-02 17:24
You can use --upgrade to downgrade:

`sudo pip3 install protonvpn-cli==2.2.2 --upgrade`

**Closed as completed** 2020-06-03 13:48 UTC
Labels: compatibility, has temporary fix
